# -*- coding: utf-8 -*-
"""AtividadeAprof1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vs1Psxx2moLEnu52rGNhDx1aHOyo4B9q
"""

import urllib.request
import string

#selecionar arquivo do livro Dom Casmurro

Texto = urllib.request.urlretrieve('https://www.gutenberg.org/cache/epub/55752/pg55752.txt', 'domcasmurro.txt')

#Abrir arquivo e deixar letras em letra minúscula

texto = open('domcasmurro.txt', 'r', encoding='utf-8')
texto = texto.read()
texto = texto.lower()

#Tirando sinais de pntuação, pois não são relevantes para a contagem de palavras

for c in string.punctuation:
  texto = texto.replace(c,' ')

texto = texto.split()

#Criando um dicionário vazio

cont = {}

#condicao para o preenchimento do dicionário

for i in texto:
  if i in cont:
    cont[i] += 1
  else:
    cont[i] = 1

#Apresentando as palavras que mais aparecem no texto

for i in sorted(cont, key = cont.get, reverse= False):
  print(i,cont[i])